export const data=[
    {
        id:1,
        name:'Product 1',
        price:10,
        image:'/images/1.jpg',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quidem.',
        category:'Category 1',
        rating:4.5,
        numReviews:10,
        numInStock:10,
        colors:['red','blue','green'],
    },
    {
        id:2,
        name:'Product 2',
        price:22,
        image:'/images/2.jpg',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quidem.',
        category:'Category 1',
        rating:2.5,
        numReviews:5,
        numInStock:10,
        colors:['red','blue','green'],
    },
    {
        id:3,
        name:'Product 3',
        price:33,
        image:'/images/3.jpg',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quidem.',
        category:'Category 1',
        rating:3.5,
        numReviews:15,
        numInStock:10,
        colors:['red','blue','green'],
    },
    {
        id:4,
        name:'Product 4',
        price:44,
        image:'/images/4.jpg',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quidem.',
        category:'Category 1',
        rating:4.5,
        numReviews:10,
        numInStock:10,
        colors:['red','blue','green'],
    },
    {
        id:5,
        name:'Product 5',
        price:55,
        image:'/images/5.jpg',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quidem.',
        category:'Category 2',
        rating:4.5,
        numReviews:10,
        numInStock:10,
        colors:['red','black','green'],
    },
    {
        id:6,
        name:'Product 6',
        price:66,
        image:'/images/6.jpg',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quidem.',
        category:'Category 2',
        rating:4.5,
        numReviews:10,
        numInStock:10,
        colors:['red','black','pink'],
    },
    {
        id:7,
        name:'Product 7',
        price:77,
        image:'/images/7.jpg',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quidem.',
        category:'Category 2',
        rating:4.5,
        numReviews:10,
        numInStock:10,
        colors:['pink','black','green'],
    },
    {
        id:8,
        name:'Product 8',
        price:88,
        image:'/images/8.jpg',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quidem.',
        category:'Category 2',
        rating:4.5,
        numReviews:10,
        numInStock:10,
        colors:['pink','black','green'],
    },
    {
        id:9,
        name:'Product 9',
        price:99,
        image:'/images/9.jpg',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quidem.',
        category:'Category 2',
        rating:4.5,
        numReviews:10,
        numInStock:10,
        colors:['pink','black','green'],
    },
    {
        id:10,
        name:'Product 10',
        price:110,
        image:'/images/10.jpg',
        description:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quidem.',
        category:'Category 2',
        rating:4.5,
        numReviews:10,
        numInStock:10,
        colors:['pink','black','green'],
    }
]